name: Build binary

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'build.sh'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'Dockerfile'

  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - 'build.sh'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'Dockerfile'

jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    env:
      ARCH: x86_64
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: "./build.sh"
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: nsm-cli-x86_64
        path: "./nsm-cli"

  build-aarch64:
    runs-on: ubuntu-latest
    env:
      ARCH: aarch64
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build
      run: "./build.sh"
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: nsm-cli-aarch64
        path: "./nsm-cli"
